apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp
    aadpodidbinding: keyvaultsampleidentity
  name: demoapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
        aadpodidbinding: keyvaultsampleidentity
      name: demoapp
    spec:
      containers:
      - name: demoapp
        image: mtrojanowskikainos/aadflexdemo:latest
        env:
        - name: AZURE_KEYVAULT_NAME
          value: keyvaultk8s
        - name: AZURE_KEYVAULT_SECRET_NAME
          value: mySecret
        - name: AZURE_KEYVAULT_SECRET_VERSION
          value: a1b2456e4ffc45be9239611f357a4321
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demoapp
  type: LoadBalancer
